@PERSON_ID=670c3021c6200c2135324ccc
###
GET http://{{baseApiUrl}}/info

###
GET http://{{baseApiUrl}}/persons

###
GET http://{{baseApiUrl}}/persons/{{PERSON_ID}}

###
GET http://{{baseApiUrl}}/persons/670c3152ef35a419d74f61099

###
DELETE http://{{baseApiUrl}}/persons/{{PERSON_ID}}

###
DELETE http://{{baseApiUrl}}/persons/670d89656ec6d04fbe390724

###
POST http://{{baseApiUrl}}/persons
content-type: application/json

{
    // "name": "Arto Hellass",
    "name": "{{$randomInt 100 110}}",
    "number": "{{$randomInt 04000000 04999999}}"
}

###
PUT http://{{baseApiUrl}}/persons/670d9b7415352d0b0b933ea1
content-type: application/json

{
    "name": "{{$randomInt 200 999}}",
    "number": "{{$randomInt 04000000 04999999}}"
}