@PERSON_ID=670c3152ef35a419d74f6108
###
GET http://{{baseApiUrl}}/info

###
GET http://{{baseApiUrl}}/persons

###
GET http://{{baseApiUrl}}/persons/{{PERSON_ID}}

###
GET http://{{baseApiUrl}}/persons/670c3152ef35a419d74f6109

###
DELETE http://{{baseApiUrl}}/persons/{{PERSON_ID}}

###
DELETE http://{{baseApiUrl}}/persons/670d896a6ec6d04fbe390730

###
POST http://{{baseApiUrl}}/persons
content-type: application/json

{
    "name": "Arto Hellass",
    // "name": "{{$randomInt 100 110}}",
    "number": "{{$randomInt 04000000 04999999}}"
}